# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot = {
    kernelParams = [
      "acpi_backlight=vendor"
      "i8042.nopnp"
      "ivrs_ioapic[4]=00:14.0"
      "ivrs_ioapic[5]=00:00.2"
      "iommu=on"
      "amd_iommu=on"
      "amdgpu.dc=1"
    ];
    blacklistedKernelModules = [
      "dell-laptop"
      "dell-smbios"
      "dell-wmi"
    ];
  };

  boot.initrd.luks.devices = {
    home = {
      device = "/dev/disk/by-uuid/c4e8c72d-d971-4296-89d3-3c942eec807a";
      preLVM = true;
      allowDiscards = true;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/aa113f7c-d0d0-40d3-a61d-0ed9a30091e8";
    fsType = "ext4";
    options = [ "noatime" "nodiratime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/19FD-EDF8";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6d087489-3e9e-4cb9-a6ce-30a4cd219307";
    fsType = "ext4";
    options = [ "noatime" "nodiratime" ];
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;

  services.xserver.videoDrivers = [ "amdgpu" ];
  services.fstrim.enable = true;
}
