# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  hardware.enableRedistributableFirmware = true;

  # kernel
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "acpi_backlight=native" ];
  boot.blacklistedKernelModules = lib.mkDefault [ "nouveau" "nvidia" ];
  boot.kernelPackages = lib.mkDefault pkgs.linuxPackages_latest;
  boot.kernel.sysctl = {
    "vm.swappiness" = lib.mkDefault 1;
  };

  services.fstrim.enable = lib.mkDefault true;

  # efi
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  #fs
  boot.initrd.luks.devices = {
    root = {
      device = "/dev/disk/by-uuid/015e3292-8572-4e9c-9fec-bd2f57ddf811";
      preLVM = true;
      allowDiscards = true;
    };
  };
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/9f4093db-2083-4c22-b1c8-643e60c7e3e3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/4057-1656";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/1f53234a-943e-48a3-b6fd-2a4a3e6e3767"; }];

  # resume
  boot.resumeDevice = "/dev/disk/by-label/swap";

  # zram
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    priority = 6;
  };

  # video
  services.xserver.videoDrivers = [ "amdgpu" ];
  hardware.opengl.enable = true;
  hardware.opengl.extraPackages = with pkgs; [ libvdpau-va-gl vaapiVdpau ];
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # audio
  hardware.pulseaudio.enable = true;

  # misc
  nix.maxJobs = 8;
}
